### PR TITLE
Aeff to push

### PR DESCRIPTION
**Pull request by jllanfranchi**
*   <span style="font-size:large">Some big ideas PISA (and PINGU) should move towards</span> (attempts made in this commit)
    *   Store important information centrally, easy for humans and software to access
        *   What I've added:
            *   MC run settings
            *   processing settings (i.e., what does "V5" processing mean?)
            *   cross sections used in simulations
    *   Store important metadata about a file within the file rather than only in filename
    *   Expose usable, intuitive interfaces to the user, hide the implementation details (need to eliminate users working with raw data structures!)
    *   Validate inputs from the user to the interface, so the underlying data is always as reasonable as possible
    *   Testing of things so that if something changes, we can easily tell of that breaks something else.
        *   I guarantee you wrote some kind of test cases when you wrote your code (maybe in an interactive shell session), unless you're perfect. So be kind to others, and put those test cases in a test() function in your module.
*   <span style="font-size:large">Generic tools</span>
    *   **utils/flavInt.py**
        *   Adds objects for working with neutrino flavors, interaction types, "kinds" (flavor + interaction type), and groups of kinds
        *   Work with these in an intuitive way:
            *   antiflav = NuFlav('numubar') # create a neutrino flavor: numubar
            *   flav = -antiflav # flavor is negative of antiflavor: numu
            *   kind = NuKind('numubar cc') # create a neutrino kind nu_mu CC
            *   kind = NuKind('nu_mu_bar_CC') # input is liberal in what it accepts
            *   kind = NuKind(-14, 1) # equivalent
            *   kind = NuKind(antiflav, 'cc') # equivalent, using NuFlav object and string as input
            *   kind = NuKind(antiflav, IntType('cc')) # equivalent, using NuFlav and IntType objects as input
            *   kind = -NuKind('numucc') # equivalent
            *   kind.tex() # LaTeX string
            *   kg0 = NuKindGroup('numucc,nue') # group of numu CC-only and nue CC+NC; both CC+NC is assumed when only a flavor is spec'd for a NuKindGroup
            *   kg1 = NuKindGroup('nutaubarcc,nuecc')
            *   kg2 = kg0 + kg1 # add groups together; does not duplicate kinds
            *   kg2.tex() # LaTeX representation of the group
            *   print kg2 # simple string representation of the group
            *   kg2.flavs() # print all flavors in the group
            *   for kind in kg2: ... # iterate over kinds in the group
        *   **FIData** (flavor/interaction type) container class for storing things previously done with raw nested dictionaries
            *   Old way:
                *   d = {f:{it:None for it in ['cc','nc']} for f in ['nue','nue_bar','numu','numu_bar',...]}
                *   d['numu_bar']['cc'] = [1,2,3]
                *   y = d['numu_bar']['cc']
            *   New way:
                *   d = FIData()
                *   d.set('numubarcc', [1,2,3])
                *   d.get('numubarcc')
                *   d.get(kind)
                *   d.get(kind, 'subkey')
                *   d.set(kind, 12)
                *   You can still do it the old way, though:
                    *   d['numu_bar']['cc'] = [4,5,6]
            *   Validation that the data structure is sane, hooks for greater validation
            *   Still have to be careful about modifying copies: since it subclasses dict, a copy is a reference to the original unless deepcopy is used
            *   AeffServiceMC.py modified to make use of this
        *   **CombinedFIData** (flavor/interaction type) container class like FIData but for storing data that is the same for multiple kinds. Intended to replace with one object/file things like each of the two sets of 8 files in the $PISA/pisa/resources/aeff/V36/cuts_V5 directory (so there would be 2 files in that dir rather than 16), and also for new systematics, etc. (And nothing to say an even higher-level container class couldn't be made containing multiples of these, and so reducing the number of separate-but-competely-bound-to-one-another files to a minimum for systematics and hence maximizing usability, user-friendliness, and -- maybe more importantly -- minimizing the inevitable human errors that will result with hundreds of separate data files being passed around.)
            *   Automatic deduplication (if you want it) looking for exactly- or approximately-equal data nodes under different kinds, and combines these together
    *   **utils/fileio.py** (modified)
        *   to_file can pass kwargs to to_hdf and to_json
        *   cPickle now uses protocol=cPickle.HIGHEST_PROTOCOL (which is important, or else generated pkl files will be buggy or impossible to read later)
    *   **utils/hdf.py** (modified)
        *   Can store metadata to HDF5 file or top-most node being written
        *   Can "write" to an already-opened h5py.File instance
        *   Just a reminder of a feature that I added some time ago: data nodes are hashed; a duplicate data node (same hash) gets hard-linked to its twin rather than being stored separately, which can drastically reduce HDF5 file sizes
        *   Add test() function, still crude
        *   To do: modify from_hdf to be able to read metadata
    *   **utils/jsons.py** (modified)
        *   Cleaned up output line
    *   **utils/utils.py** (modified)
        *   recEq, recAllclose: recursively verify equality / close-to-equality for data living in nested dicts, lists, and any combination thereof
        *   engfmt: engineering formatting of numbers
        *   timediffstamp: smart time difference stamps
        *   timestamp: easily generate ISO-8601 timestamps
        *   *hrlist*: convert lists of numbers to/from human-readable lists
            *   [1,2,3,5,6,7] <--> "1-3,5-7"
        *   expandPath: os.path.expandvars(os.path.expanduser(x))
        *   mkdir: make a directory with default permissions and recursively add missing parent directories if they don't exist; don't raise an exception (but print warning) if the dir already exists
        *   nsort: sort strings like "0xyz" before "0010xyz"
        *   findFiles: find a file by matching a string, regex, optionaly recursively
*   <span style="font-size:large">Cross sections</span>
    *   **utils/crossSections.py** (new) **: CrossSections** class
        *   Class for dealing with cross sections easily and consistently
        *   Load, save cross sections from/to PISA JSON flav/int data files
        *   Load cross sections from ROOT file as formatted by Ken (see code for details of what it expects)
    *   **resources/cross_sections/cross_sections.json** (new)
        *   Stores multiple versions of cross sections in a single location, builds off of standard PISA FIData dict/JSON file + single 'energy' key to avoid repetition
*   <span style="font-size:large">MC simulation run settings</span>
    *   **utils/mcSimRunSettings.py** (new) **: MCSimRunSettings** class
        *   Load, save, store, and some convenience functions for working with monte carlo sim run settings.
    *   **resources/events/mc_sim_run_settings.json** (new)
        *   Settings stored by detector ('pingu', 'deepcore', etc) / run # ('388', '389', etc.)
        *   Info on what geometry was used (e.g., "v36")
        *   Simulation settings: energy, azimuth, zenith ranges; energy spectrum; which cross sections were used; what flavors are present; nu-to-(nu+nubar) fraction, # events/file, # files, genie physical factor, genie prescale factor
*   <span style="font-size:large">Data/MC processing parameters used</span>
    *   **utils/dataProcParams.py** (new)
        *   allows user to work with HDF5 files that were converted from I3 files by dataio
            *   retrieve "important" data from HDF'd I3 files in a consistent way regardless of processing that was applied
            *   Fairly generic mechanism for simple user-defined cuts to be created, applied to data, and stored for easy reference later so others can see what logic was applied
                *   Some validation to help user get it right
        *   Load, save, and work with parameters used in data processing (from/to json file defined below)
    *   **resources/events/data_proc_params.json** (new)
        *   Central location to store things that define data processing settings
        *   Includes field name mappings from what's in the I3 files to what gets used in analysis
        *   Defines what's meant by standard cuts such as "bgrej" and "analysis"
        *   Other cuts are easily added in the file which might be particular to a processing version
*   <span style="font-size:large">PISA events files: generating & working with them</span>
    *   **utils/events.py** (new) **: Events** class, subclasses FIData
        *   Class for loading, working with, and saving PISA "standard" events files
        *   Subclasses FIData; things like the following work easily:
            *   events.get('numucc')
            *   events.get('numu')
        *   Includes important metadata so info about what was used to create the file is not only included in the filename; this is attached to / read from the HDF5 file when the save()/load() methods are invoked
        *   Simple validation of the underlying data / data structure via FIData class
    *   **i3utils/make_events_file.py** (new; replaces **_make_aeff_mc_file.py_** which was deleted)
        *   ALWAYS generate 3 events files upon invocation so as to avoid users needing a file but not having it (and then choosing the wrong file)
            *   User provides a directory, _not_ which files to produce _nor_ the file names to use
            *   Maximally descriptive naming convention forced upon the user
        *   Metadata stored as HDF5 attributs of highest-level entity in HDF5 file
        *   The 3 events files combine events in the ways we've done previously in PISA:
            *   not at all
                *   **events__pingu__v36__runs_388-390__proc_v5__unjoined.hdf5**
            *   nux+nuxbar CC as 3 separate groups and nuall+nuallbar NC as a single group
                *   **events__pingu__v36__runs_388-390__proc_v5__joined_G_nue_cc+nuebar_cc_G_numu_cc+numubar_cc_G_nutau_cc+nutaubar_cc_G_nuall_nc+nuallbar_nc.hdf5**
            *   nux, nuxbar CC completely separate from one another, but nuall NC joined and nuallbar NC joined separately
                *   **events__pingu__v36__runs_388-390__proc_v5__joined_G_nuall_nc_G_nuallbar_nc.hdf5**
        *   weighted_aeff field generated according to flavor- and/or int-type-combination rules enumerated in my PINGU analysis call presentations
        *   Attaches relevant metadata about the MC source data used to create the file (detector, geometry, runs, processing version applied, cuts applied)
    *   **resources/settings/template_settings/V36_LoI_*.json** (modified)
        *   Modified to make use of the events files I generate with above script
            *   events/V36_weighted_aeff_joined_nu_nubar.hdf5 -->
        *   Have NOT modified V15 settings, have not generated events files for that either

### CODE REVIEW

**Comment by sboeser** [comment]
Hi Justin,
sorry for taking so long for getting at this. As I mentioned on the call, I think this is all great stuff. The only changes I'd propose are:

* [ ] change the `NuKind` to `NuFlavInt` or some other name reflecting that this has _flavour_ and _interaction type_ information.
* [ ] same for `NuKindGroup`
* [ ] change `FIData` to `FlavIntData` or  some other name reflecting that this has _flavour_ and _interaction type_ information.
* [ ] same for `CombinedFIData`

Then there was one point in the discussion I remember where you said you'd write out an error message, while I thought this should throw an exception. But I can't remember what that was?

Finally, the information on your slides already provides great documentation on all the features. Can we just
* [ ] copy-paste the text starting from page 5 to a markdown file that we put somewhere in the docs directory, e.g. in `docs/utils/flavour_interaction_types.md` ?

Cheers and thanks,
Sebastian

**Comment by jllanfranchi** [comment]
@sboeser : The point in the discussion we'd discussed turning into an error involved the CombinedFlavIntData object. This container can hold data that is redundant for multiple flavints.

I believe the behavior should be an exception is raised if the user attempts to ***set*** data for a strict subset of grouped-together flavints. However, I believe a warning is appropriate if a user attempts to ***get*** data for a strict subset of grouped-together flavints, as that seems a reasonable thing to do. Do you agree?

Thanks, Justin

**Comment by sboeser** [comment]
yes - thanks!

**Comment by jllanfranchi** [comment]
@sboeser I decided that a warning for ***get***ting the data for a strict subset of grouped NuFlavInts in a CombinedFlavIntData object will output a logging.debug message and not a warning. Easily changed, but it could put a bunch of unneeded info in the "warning" bin that can be ignored and hence will obscure more warning-worthy messages. I still have to add documentation and run a few tests, so don't merge yet.

**Comment by jllanfranchi** [comment]
Note also that I realize I'm bringing in what I believe are the last changes Tim made before he left, as I was using his master branch after the project had forked to use yours as the master. I believe all of these changes live in the analysis/ folder and shouldn't affect anything else, but I'm not 100% sure of that.

**Comment by jllanfranchi** [comment]
@sboeser I believe the code is ready to be merged now/

**Comment by sboeser** [comment]
@jllanfranchi Thanks for this great set of utils!

**Comment by jllanfranchi** [comment]
You're welcome. If anything breaks because of these changes, please let me know.

**Pull request merged**
